// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: aivg/satellite/v1/audio.proto

#include "aivg/satellite/v1/audio.pb.h"
#include "aivg/satellite/v1/audio.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace aivg {
namespace satellite {
namespace v1 {

static const char* Audio_method_names[] = {
  "/aivg.satellite.v1.Audio/Stream",
};

std::unique_ptr< Audio::Stub> Audio::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Audio::Stub> stub(new Audio::Stub(channel, options));
  return stub;
}

Audio::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Stream_(Audio_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::BIDI_STREAMING, channel)
  {}

::grpc::ClientReaderWriter< ::aivg::satellite::v1::ClientFrame, ::aivg::satellite::v1::ServerFrame>* Audio::Stub::StreamRaw(::grpc::ClientContext* context) {
  return ::grpc::internal::ClientReaderWriterFactory< ::aivg::satellite::v1::ClientFrame, ::aivg::satellite::v1::ServerFrame>::Create(channel_.get(), rpcmethod_Stream_, context);
}

void Audio::Stub::async::Stream(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::aivg::satellite::v1::ClientFrame,::aivg::satellite::v1::ServerFrame>* reactor) {
  ::grpc::internal::ClientCallbackReaderWriterFactory< ::aivg::satellite::v1::ClientFrame,::aivg::satellite::v1::ServerFrame>::Create(stub_->channel_.get(), stub_->rpcmethod_Stream_, context, reactor);
}

::grpc::ClientAsyncReaderWriter< ::aivg::satellite::v1::ClientFrame, ::aivg::satellite::v1::ServerFrame>* Audio::Stub::AsyncStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::aivg::satellite::v1::ClientFrame, ::aivg::satellite::v1::ServerFrame>::Create(channel_.get(), cq, rpcmethod_Stream_, context, true, tag);
}

::grpc::ClientAsyncReaderWriter< ::aivg::satellite::v1::ClientFrame, ::aivg::satellite::v1::ServerFrame>* Audio::Stub::PrepareAsyncStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncReaderWriterFactory< ::aivg::satellite::v1::ClientFrame, ::aivg::satellite::v1::ServerFrame>::Create(channel_.get(), cq, rpcmethod_Stream_, context, false, nullptr);
}

Audio::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Audio_method_names[0],
      ::grpc::internal::RpcMethod::BIDI_STREAMING,
      new ::grpc::internal::BidiStreamingHandler< Audio::Service, ::aivg::satellite::v1::ClientFrame, ::aivg::satellite::v1::ServerFrame>(
          [](Audio::Service* service,
             ::grpc::ServerContext* ctx,
             ::grpc::ServerReaderWriter<::aivg::satellite::v1::ServerFrame,
             ::aivg::satellite::v1::ClientFrame>* stream) {
               return service->Stream(ctx, stream);
             }, this)));
}

Audio::Service::~Service() {
}

::grpc::Status Audio::Service::Stream(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::aivg::satellite::v1::ServerFrame, ::aivg::satellite::v1::ClientFrame>* stream) {
  (void) context;
  (void) stream;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace aivg
}  // namespace satellite
}  // namespace v1

