// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: aivg/satellite/v1/audio.proto
// Original file comments:
// Canonical audio-plane contract for the AIVG gRPC satellite transport.
//
// Phase 1 of feature 021. SINGLE SOURCE OF TRUTH (FR-001): the gateway
// (Python, aivg_core.transports.grpc) and every native client (C++, in the
// aivg-devices repo) generate their bindings from THIS file — the contract
// cannot drift. Ships verbatim to repo-root proto/aivg/satellite/v1/audio.proto.
//
// Wire compatibility (FR-004): additive only. New fields/event kinds use new
// tag numbers; never renumber or reuse a tag; never change a field's type.
// Reserve removed tags.
//
#ifndef GRPC_aivg_2fsatellite_2fv1_2faudio_2eproto__INCLUDED
#define GRPC_aivg_2fsatellite_2fv1_2faudio_2eproto__INCLUDED

#include "aivg/satellite/v1/audio.pb.h"

#include <functional>
#include <grpcpp/generic/async_generic_service.h>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/client_context.h>
#include <grpcpp/completion_queue.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/codegen/proto_utils.h>
#include <grpcpp/impl/rpc_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/impl/codegen/status.h>
#include <grpcpp/support/stub_options.h>
#include <grpcpp/support/sync_stream.h>

namespace aivg {
namespace satellite {
namespace v1 {

// One bidirectional stream per voice session. The session_id (minted by the
// management plane) is sent in the first ClientFrame (SessionHeader) and keys
// the stream to an adopted satellite's open session (FR-006).
class Audio final {
 public:
  static constexpr char const* service_full_name() {
    return "aivg.satellite.v1.Audio";
  }
  class StubInterface {
   public:
    virtual ~StubInterface() {}
    std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::aivg::satellite::v1::ClientFrame, ::aivg::satellite::v1::ServerFrame>> Stream(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriterInterface< ::aivg::satellite::v1::ClientFrame, ::aivg::satellite::v1::ServerFrame>>(StreamRaw(context));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::aivg::satellite::v1::ClientFrame, ::aivg::satellite::v1::ServerFrame>> AsyncStream(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::aivg::satellite::v1::ClientFrame, ::aivg::satellite::v1::ServerFrame>>(AsyncStreamRaw(context, cq, tag));
    }
    std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::aivg::satellite::v1::ClientFrame, ::aivg::satellite::v1::ServerFrame>> PrepareAsyncStream(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriterInterface< ::aivg::satellite::v1::ClientFrame, ::aivg::satellite::v1::ServerFrame>>(PrepareAsyncStreamRaw(context, cq));
    }
    class async_interface {
     public:
      virtual ~async_interface() {}
      virtual void Stream(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::aivg::satellite::v1::ClientFrame,::aivg::satellite::v1::ServerFrame>* reactor) = 0;
    };
    typedef class async_interface experimental_async_interface;
    virtual class async_interface* async() { return nullptr; }
    class async_interface* experimental_async() { return async(); }
   private:
    virtual ::grpc::ClientReaderWriterInterface< ::aivg::satellite::v1::ClientFrame, ::aivg::satellite::v1::ServerFrame>* StreamRaw(::grpc::ClientContext* context) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::aivg::satellite::v1::ClientFrame, ::aivg::satellite::v1::ServerFrame>* AsyncStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) = 0;
    virtual ::grpc::ClientAsyncReaderWriterInterface< ::aivg::satellite::v1::ClientFrame, ::aivg::satellite::v1::ServerFrame>* PrepareAsyncStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) = 0;
  };
  class Stub final : public StubInterface {
   public:
    Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());
    std::unique_ptr< ::grpc::ClientReaderWriter< ::aivg::satellite::v1::ClientFrame, ::aivg::satellite::v1::ServerFrame>> Stream(::grpc::ClientContext* context) {
      return std::unique_ptr< ::grpc::ClientReaderWriter< ::aivg::satellite::v1::ClientFrame, ::aivg::satellite::v1::ServerFrame>>(StreamRaw(context));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::aivg::satellite::v1::ClientFrame, ::aivg::satellite::v1::ServerFrame>> AsyncStream(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::aivg::satellite::v1::ClientFrame, ::aivg::satellite::v1::ServerFrame>>(AsyncStreamRaw(context, cq, tag));
    }
    std::unique_ptr<  ::grpc::ClientAsyncReaderWriter< ::aivg::satellite::v1::ClientFrame, ::aivg::satellite::v1::ServerFrame>> PrepareAsyncStream(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) {
      return std::unique_ptr< ::grpc::ClientAsyncReaderWriter< ::aivg::satellite::v1::ClientFrame, ::aivg::satellite::v1::ServerFrame>>(PrepareAsyncStreamRaw(context, cq));
    }
    class async final :
      public StubInterface::async_interface {
     public:
      void Stream(::grpc::ClientContext* context, ::grpc::ClientBidiReactor< ::aivg::satellite::v1::ClientFrame,::aivg::satellite::v1::ServerFrame>* reactor) override;
     private:
      friend class Stub;
      explicit async(Stub* stub): stub_(stub) { }
      Stub* stub() { return stub_; }
      Stub* stub_;
    };
    class async* async() override { return &async_stub_; }

   private:
    std::shared_ptr< ::grpc::ChannelInterface> channel_;
    class async async_stub_{this};
    ::grpc::ClientReaderWriter< ::aivg::satellite::v1::ClientFrame, ::aivg::satellite::v1::ServerFrame>* StreamRaw(::grpc::ClientContext* context) override;
    ::grpc::ClientAsyncReaderWriter< ::aivg::satellite::v1::ClientFrame, ::aivg::satellite::v1::ServerFrame>* AsyncStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq, void* tag) override;
    ::grpc::ClientAsyncReaderWriter< ::aivg::satellite::v1::ClientFrame, ::aivg::satellite::v1::ServerFrame>* PrepareAsyncStreamRaw(::grpc::ClientContext* context, ::grpc::CompletionQueue* cq) override;
    const ::grpc::internal::RpcMethod rpcmethod_Stream_;
  };
  static std::unique_ptr<Stub> NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options = ::grpc::StubOptions());

  class Service : public ::grpc::Service {
   public:
    Service();
    virtual ~Service();
    virtual ::grpc::Status Stream(::grpc::ServerContext* context, ::grpc::ServerReaderWriter< ::aivg::satellite::v1::ServerFrame, ::aivg::satellite::v1::ClientFrame>* stream);
  };
  template <class BaseClass>
  class WithAsyncMethod_Stream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithAsyncMethod_Stream() {
      ::grpc::Service::MarkMethodAsync(0);
    }
    ~WithAsyncMethod_Stream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Stream(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::aivg::satellite::v1::ServerFrame, ::aivg::satellite::v1::ClientFrame>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStream(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::aivg::satellite::v1::ServerFrame, ::aivg::satellite::v1::ClientFrame>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  typedef WithAsyncMethod_Stream<Service > AsyncService;
  template <class BaseClass>
  class WithCallbackMethod_Stream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithCallbackMethod_Stream() {
      ::grpc::Service::MarkMethodCallback(0,
          new ::grpc::internal::CallbackBidiHandler< ::aivg::satellite::v1::ClientFrame, ::aivg::satellite::v1::ServerFrame>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->Stream(context); }));
    }
    ~WithCallbackMethod_Stream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Stream(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::aivg::satellite::v1::ServerFrame, ::aivg::satellite::v1::ClientFrame>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::aivg::satellite::v1::ClientFrame, ::aivg::satellite::v1::ServerFrame>* Stream(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef WithCallbackMethod_Stream<Service > CallbackService;
  typedef CallbackService ExperimentalCallbackService;
  template <class BaseClass>
  class WithGenericMethod_Stream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithGenericMethod_Stream() {
      ::grpc::Service::MarkMethodGeneric(0);
    }
    ~WithGenericMethod_Stream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Stream(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::aivg::satellite::v1::ServerFrame, ::aivg::satellite::v1::ClientFrame>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
  };
  template <class BaseClass>
  class WithRawMethod_Stream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawMethod_Stream() {
      ::grpc::Service::MarkMethodRaw(0);
    }
    ~WithRawMethod_Stream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Stream(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::aivg::satellite::v1::ServerFrame, ::aivg::satellite::v1::ClientFrame>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    void RequestStream(::grpc::ServerContext* context, ::grpc::ServerAsyncReaderWriter< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* stream, ::grpc::CompletionQueue* new_call_cq, ::grpc::ServerCompletionQueue* notification_cq, void *tag) {
      ::grpc::Service::RequestAsyncBidiStreaming(0, context, stream, new_call_cq, notification_cq, tag);
    }
  };
  template <class BaseClass>
  class WithRawCallbackMethod_Stream : public BaseClass {
   private:
    void BaseClassMustBeDerivedFromService(const Service* /*service*/) {}
   public:
    WithRawCallbackMethod_Stream() {
      ::grpc::Service::MarkMethodRawCallback(0,
          new ::grpc::internal::CallbackBidiHandler< ::grpc::ByteBuffer, ::grpc::ByteBuffer>(
            [this](
                   ::grpc::CallbackServerContext* context) { return this->Stream(context); }));
    }
    ~WithRawCallbackMethod_Stream() override {
      BaseClassMustBeDerivedFromService(this);
    }
    // disable synchronous version of this method
    ::grpc::Status Stream(::grpc::ServerContext* /*context*/, ::grpc::ServerReaderWriter< ::aivg::satellite::v1::ServerFrame, ::aivg::satellite::v1::ClientFrame>* /*stream*/)  override {
      abort();
      return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
    }
    virtual ::grpc::ServerBidiReactor< ::grpc::ByteBuffer, ::grpc::ByteBuffer>* Stream(
      ::grpc::CallbackServerContext* /*context*/)
      { return nullptr; }
  };
  typedef Service StreamedUnaryService;
  typedef Service SplitStreamedService;
  typedef Service StreamedService;
};

}  // namespace v1
}  // namespace satellite
}  // namespace aivg


#endif  // GRPC_aivg_2fsatellite_2fv1_2faudio_2eproto__INCLUDED
