# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import audio_pb2 as audio__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in audio_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AudioStub:
    """One bidirectional stream per voice session. The session_id (minted by the
    management plane) is sent in the first ClientFrame (SessionHeader) and keys
    the stream to an adopted satellite's open session (FR-006).
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Stream = channel.stream_stream(
                '/aivg.satellite.v1.Audio/Stream',
                request_serializer=audio__pb2.ClientFrame.SerializeToString,
                response_deserializer=audio__pb2.ServerFrame.FromString,
                _registered_method=True)


class AudioServicer:
    """One bidirectional stream per voice session. The session_id (minted by the
    management plane) is sent in the first ClientFrame (SessionHeader) and keys
    the stream to an adopted satellite's open session (FR-006).
    """

    def Stream(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AudioServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Stream': grpc.stream_stream_rpc_method_handler(
                    servicer.Stream,
                    request_deserializer=audio__pb2.ClientFrame.FromString,
                    response_serializer=audio__pb2.ServerFrame.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aivg.satellite.v1.Audio', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aivg.satellite.v1.Audio', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Audio:
    """One bidirectional stream per voice session. The session_id (minted by the
    management plane) is sent in the first ClientFrame (SessionHeader) and keys
    the stream to an adopted satellite's open session (FR-006).
    """

    @staticmethod
    def Stream(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/aivg.satellite.v1.Audio/Stream',
            audio__pb2.ClientFrame.SerializeToString,
            audio__pb2.ServerFrame.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
