# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import management_pb2 as management__pb2

GRPC_GENERATED_VERSION = '1.81.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in management_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ManagementStub:
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Register = channel.unary_unary(
                '/aivg.satellite.v1.Management/Register',
                request_serializer=management__pb2.RegisterRequest.SerializeToString,
                response_deserializer=management__pb2.RegisterReply.FromString,
                _registered_method=True)
        self.Control = channel.stream_stream(
                '/aivg.satellite.v1.Management/Control',
                request_serializer=management__pb2.StateUpdate.SerializeToString,
                response_deserializer=management__pb2.ControlMessage.FromString,
                _registered_method=True)


class ManagementServicer:
    """Missing associated documentation comment in .proto file."""

    def Register(self, request, context):
        """Device registers; gateway returns adoption state + a session-minting handle.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Control(self, request_iterator, context):
        """Long-lived bidi control channel (replaces /satellite/ws for native).
        Device pushes state/heartbeat/wake-turn up; gateway pushes control down.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ManagementServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Register': grpc.unary_unary_rpc_method_handler(
                    servicer.Register,
                    request_deserializer=management__pb2.RegisterRequest.FromString,
                    response_serializer=management__pb2.RegisterReply.SerializeToString,
            ),
            'Control': grpc.stream_stream_rpc_method_handler(
                    servicer.Control,
                    request_deserializer=management__pb2.StateUpdate.FromString,
                    response_serializer=management__pb2.ControlMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'aivg.satellite.v1.Management', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('aivg.satellite.v1.Management', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Management:
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Register(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/aivg.satellite.v1.Management/Register',
            management__pb2.RegisterRequest.SerializeToString,
            management__pb2.RegisterReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Control(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/aivg.satellite.v1.Management/Control',
            management__pb2.StateUpdate.SerializeToString,
            management__pb2.ControlMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
